import type { Metadata } from "next";
import { poppins,jost, mono, plusJakartaSans, dancingScript, playfair} from "@/lib/fonts"
// @ts-ignore: allow side-effect css import without type declarations
import "./globals.css";
import Providers from "@/components/providers/providers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="afterInteractive"
        />
      </head>
      <body
        className={`bg-background text-foreground ${poppins.variable} ${jost.variable} ${mono.variable} ${plusJakartaSans.variable} ${dancingScript.variable} ${playfair.variable} antialiased`}
      >
        <Providers>
          
          {children}

        </Providers>
      </body>
    </html>
  );
}
